### ISSUE TITLE
CI pipeline

### ISSUE THREAD

**Issue by mike-north** [DockYard/courier_web#8]
Looks like travis-ci is not in use. I'd feel more confident about using this if I saw a friendly green status :)

**Comment by bcardarella** [comment]
Closed by #7

**Comment by mike-north** [comment]
I don't think Travis is listening to commits

**Comment by bcardarella** [comment]
hmmm... let me check the settings

**Comment by ghost** [comment]
Brian Carderella does not need CI, just his presence makes all tests pass.

**Comment by bcardarella** [comment]
If only.

Looks like the rename didn't carry through on travis, I've turned it back on. It should be OK with `master` on Courier but I'm going to update all deps to confirm.
